# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	LogPath     = "logs/gf"

# Logger.
[logger]
    Path        = "logs"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:123456@tcp(127.0.0.1:13306)/test"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "logs/sql"
        Level  = "all"
        Stdout = true