

services:
  mysql:
    # mysql:5.7 linux/arm64 image is unavailable.
    image: mysql:8.0.42
    container_name: gfstudy-mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TIMEZONE}
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --tls_version="TLSv1.2,TLSv1.3"
      --init-file /data/application/init.sql
      --binlog_expire_logs_seconds=604800
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - gf_mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - gfstudy
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: on-failure

  redis:
    image: redis:8.0.2
    container_name: gfstudy-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru
    env_file: .env
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - gf_redis_data:/data
    networks:
      - gfstudy
    restart: on-failure

volumes:
  gf_mysql_data:
    driver: local
  gf_redis_data:
    driver: local

networks:
  gfstudy:
    driver: bridge