### 函数注册1
POST http://localhost:8199/handler

### 函数注册2
GET http://localhost:8199/handler/abc

### 函数注册3
GET http://localhost:8199/handler/a/update

### 函数注册4
GET http://localhost:8199/handler/a/add

### 函数注册5
GET http://localhost:8199/handler/list/11.html

### 函数注册：方法
GET http://localhost:8199/handler/total

### 对象注册，默认访问index
POST http://localhost:8199/object/

### 对象注册，直接访问Index
POST http://localhost:8199/object/index

### 对象注册，访问show方法
POST http://localhost:8199/object/show

### 分组注册，默认访问index
PUT http://localhost:8199/group/all

### 分组注册，直接访问Index
GET http://localhost:8199/group/get

### 分组注册，访问show方法
POST http://localhost:8199/group/post

### 规范注册
GET http://localhost:8199/user/hello?name=fox
