### 常规注册
POST http://localhost:8199/hello

###
GET http://localhost:8199/abc

###
GET http://localhost:8199/a/update

###
GET http://localhost:8199/a/add

###
GET http://localhost:8199/user/list/11.html

### 方法注册
GET http://localhost:8199/total

### 对象注册，默认访问index
POST http://localhost:8199/object/

### 对象注册，直接访问Index
POST http://localhost:8199/object/index

### 对象注册，访问show方法
POST http://localhost:8199/object/show

### 分组，默认访问index
PUT http://localhost:8199/api/all

### 对象注册，直接访问Index
GET http://localhost:8199/api/get

### 对象注册，访问show方法
POST http://localhost:8199/api/post

### request and response
POST http://localhost:8199/test
sex:man

name=liubang&age=18

###
